pipeline:
  build:
    image: codeberg.org/julian21/ci-typescript-webpack:edge
    commands:
      - npm install --save-dev typescript ts-loader
      - npx webpack --config webpack.config.js
#      - minify dist/pronounsPage.js > dist/pronounsPage.min.js
  jest:
    image: codeberg.org/julian21/ci-typescript-jest:edge
    commands:
      - npm install node-fetch
      - npx jest --config=jest.config.js
  uploadEdge:
    image: woodpeckerci/plugin-s3
    settings:
      bucket: cdn
      access_key:
        from_secret: s3_access_key_id
      secret_key:
        from_secret: s3_secret_access_key
      source: dist/*
      target: /scripts/pronouns.page/edge/
      path_style: true
      endpoint: http://192.2.99.21:9000
      region: eu-DE
    when:
      - event: push
        branch: main
  uploadCi:
    depends_on: jest
    image: woodpeckerci/plugin-s3
    settings:
      bucket: cdn
      access_key:
        from_secret: s3_access_key_id
      secret_key:
        from_secret: s3_secret_access_key
      source: dist/*
      target: /scripts/pronouns.page/ci/${CI_BUILD_NUMBER}
      path_style: true
      endpoint: http://192.2.99.21:9000
      region: eu-DE
    when:
      - event: push
        branch: main